theme = 'hyde'
baseURL = "https://pop-ecx.github.io/"
languageCode = "en-us"
title = "pop-ecx"
[params]
  description = "Break, Comprehend, Build"
  github = "https://github.com/pop-ecx"
  linkedin = "https://www.linkedin.com/in/oliver-mulwa"
  authorImage = "/images/scarab.jpeg"
## Main Menu
[[menu.main]]
    name = "Posts"
    weight = 100
    identifier = "posts"
    url = "/posts/"
[[menu.main]]
    name = "About"
    identifier = "about"
    weight = 200
    url = "/about/"
